### ISSUE TITLE
节点测试已完成，请求官方发放测试币

### ISSUE THREAD

**Issue by Freeaii** [abelbeertech/abel-bkchain#5]
5CJm6mtto3thJGvbwFqmYEjhfumUo888SYbjBckYdUSexAUm

**Comment by 20191001** [comment]
It seems v0.0.2testnet accounts still without test coins

---原始邮件---
发件人: "Poison-Abel"<notifications@github.com&gt;
发送时间: 2020年11月28日(周六) 上午9:44
收件人: "abelbeertech/abel-bkchain"<abel-bkchain@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [abelbeertech/abel-bkchain] 节点测试已完成，请求官方发放测试币 (#5)




 
5CJm6mtto3thJGvbwFqmYEjhfumUo888SYbjBckYdUSexAUm
